/********************* ROLES *********************/

/********************* UDFS ***********************/

/********************* FUNCTIONS **********************/

/****************** SEQUENCES ********************/

/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

/******************* PACKAGES ******************/

/******************** TABLES *********************/

CREATE TABLE PARTICIPANTE 
(
  PARTICIPANTE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
  CEDULA VARCHAR(13) NOT NULL,
  NOMBRES VARCHAR(45) NOT NULL,
  APELLIDOS VARCHAR(45) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  TELEFONO VARCHAR(17),
  CELULAR VARCHAR(17),
  DIRECCION VARCHAR(256),
  ESTADO_CIVIL CHAR(1),
  CORREO_ELECTRONICO VARCHAR(256),
  SEXO CHAR(1) NOT NULL,
  CURSO VARCHAR(256) NOT NULL,
  MODULO_1 DECIMAL(5,2) NOT NULL,
  MODULO_2 DECIMAL(5,2) NOT NULL,
  MODULO_3 DECIMAL(5,2) NOT NULL,
  MODULO_4 DECIMAL(5,2) NOT NULL,
  CONSTRAINT INTEG_25 PRIMARY KEY (PARTICIPANTE_ID)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

/******************** DB TRIGGERS ********************/

/******************** DDL TRIGGERS ********************/


ALTER TABLE PARTICIPANTE ADD PROMEDIO COMPUTED BY ((modulo_1+modulo_2+modulo_3+modulo_4)/4);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PARTICIPANTE TO  SYSDBA WITH GRANT OPTION;

